language: node_js
node_js:
  - "10"

install:
  - npm install

jobs:
  include:
      - name: "Unit Tests"
        script: npm test
      - name: "Ecmascript check"
        script: npm run test:es
      - name: "Size check"
        script: npm run test:size
      - name: "Lint"
        script: npm run lint
      - name: "Docs"
        script: npm run doc
      - name: "Benchmark Test"
        script: npm run benchmark
      - name: "Audit"
        script: npm audit || echo \"audit found some vulnerabilities.\"
